ambity/ambity/urls.py
import django.contrib.admin
import django.urls

import dialogs.urls


urlpatterns = [
    django.urls.path(
        "admin/",
        django.contrib.admin.site.urls,
    ),
    django.urls.path(
        "dialogs/",
        django.urls.include(dialogs.urls)
    )
]

ambity/dialogs/urls.py
import django.urls

import dialogs.views


app_name = "dialogs"

urlpatterns = [
    django.urls.path(
        "create_dialog/",
        dialogs.views.CreateDialogView.as_view(),
        name="create_dialog",
    ),
    django.urls.path(
        "",
        dialogs.views.DialogListView.as_view(),
        name="dialog_list",
    ),
    django.urls.path(
        "<pk>/",
        dialogs.views.DialogDetailView.as_view(),
        name="dialog_detail",
    ),
]

ambity/dialogs/models.py
import django.db.models


class Contact(django.db.models.Model):
    full_name = django.db.models.CharField(
        verbose_name="ФИО",
        max_length=93,
    )
    phone = django.db.models.CharField(
        verbose_name="Телефон",
        max_length=15,
    )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class Operator(django.db.models.Model):
    full_name = django.db.models.CharField(
        verbose_name="ФИО",
        max_length=93,
    )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'оператор'
        verbose_name_plural = 'операторы'


class Transcription(django.db.models.Model):
    operator_transcription = django.db.models.JSONField(
        "транскрипция оператора",
        null=True,
        blank=True,
    )
    contact_transcription = django.db.models.JSONField(
        "транскрипция клиента",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"транскрипция {self.id}"

    class Meta:
        verbose_name = 'транскрипция'
        verbose_name_plural = 'транскрипции'


class Conversation(django.db.models.Model):
    transcription = django.db.models.OneToOneField(
        Transcription,
        on_delete=django.db.models.CASCADE,
        related_name="conversation",
    )
    contact_audio = django.db.models.URLField()

    def __str__(self):
        return f"разговор {self.id}"

    class Meta:
        verbose_name = 'разговор'
        verbose_name_plural = 'разговоры'


class DialogCard(django.db.models.Model):
    CHOICES = (
        ("New", "Новое"),
        ("Work", "В работе"),
        ("Done", "Обработано"),
    )
    call_date = django.db.models.DateTimeField(
        verbose_name="Дата и время звонка",
    )
    contact = django.db.models.ForeignKey(
        Contact,
        on_delete=django.db.models.CASCADE,
    )
    operator = django.db.models.ForeignKey(
        Operator,
        on_delete=django.db.models.CASCADE,
    )
    conversation = django.db.models.ForeignKey(
        Conversation,
        on_delete=django.db.models.CASCADE,
    )
    status = django.db.models.CharField(
        max_length=512,
        choices=CHOICES,
        default="Новое",
    )
    def __str__(self):
        return f"Диалог {self.id}"

    class Meta:
        verbose_name = 'карточка контакта'
        verbose_name_plural = 'карточки контактов'

ambity/dialogs/views.py
import django.views.generic
import dialogs.models
import requests
import django.urls
import django.shortcuts

import dialogs.transcription


class DialogListView(django.views.generic.ListView):
    template_name = "dialogs/list.html"
    model = dialogs.models.DialogCard
    context_object_name = "dialog_list"

    def get_queryset(self):
        return super().get_queryset()


class DialogDetailView(django.views.generic.DetailView):
    template_name = "dialogs/detail.html"
    model = dialogs.models.DialogCard
    context_object_name = "dialog"

    def get_queryset(self):
        return super().get_queryset()


class CreateDialogView(django.views.View):

    def get(self, request, *args, **kwargs):
        response_data = requests.get("http://hackathon.ambity.ru/api/contact").json()

        transcripted_dialog = dialogs.transcription.transcript(response_data["contact_audio"])

        operator_transcription=list(map(lambda x: x.text, filter(lambda x: x.speaker == "B", transcripted_dialog)))
        print(operator_transcription)
        contact_transcription=list(map(lambda x: x.text, filter(lambda x: x.speaker == "A", transcripted_dialog)))
        print(contact_transcription)

        contact_full_name = contact_transcription[1][len("Меня зовут") + 1:].rstrip() # не надёжный хардкод (доработать)

        contact_model = dialogs.models.Contact(
            full_name=contact_full_name,
            phone=response_data["client_phone"],
        )
        operator_model = dialogs.models.Operator(
            full_name=response_data["operator_fio"].split(",")[0],
        )
        transcription_model = dialogs.models.Transcription(
            operator_transcription=operator_transcription,
            contact_transcription=contact_transcription,
        )
        conversation_model = dialogs.models.Conversation(
            transcription=transcription_model,
            contact_audio="http://hackathon.ambity.ru/hackathon/public/audio/zapis418.mp3",
        )
        dialog_model = dialogs.models.DialogCard(
            call_date=response_data["call_date"],
            contact=contact_model,
            operator=operator_model,
            conversation=conversation_model,
        )

        contact_model.save()
        operator_model.save()
        transcription_model.save()
        conversation_model.save()
        dialog_model.save()

        return django.shortcuts.redirect(
            django.urls.reverse_lazy("dialogs:dialog_detail", args=[dialog_model.pk])
        )

ambity/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>Амбити | Карточки контактов</title>
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'img/favicon/apple-touch-icon.ico' %}">
    <link rel="icon" type="image/ico" href="{% static 'img/favicons/favicon-32x32.ico' %}">
    <link rel="icon" type="image/ico" href="{% static 'img/favicons/favicon-16x16.ico' %}">
    <link rel="manifest" href="{% static 'img/favicons/site.webmanifest' %}">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      {% block content %}content{% endblock %}
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

ambity/templates/dialogs/detail.html
{% extends "base.html" %}
{% block content %}
<p>{{ dialog }}</p>
<p>{{ dialog.call_date }}</p>
<p>{{ dialog.contact.full_name }}</p>
<p>{{ dialog.contact.phone }}</p>
<p>{{ dialog.operator.full_name }}</p>
<p>{{ dialog.conversation.contact_audio }}</p>
<p>{{ dialog.conversation.transcription.operator_transcription }}</p>
<p>{{ dialog.conversation.transcription.contact_transcription }}</p>

{% endblock content %}

ambity/templates/dialogs/list.html
{% extends "base.html" %}
{% block content %}
<div class="container px-4 py-5" id="custom-cards">
  <h2 class="pb-2 border-bottom"> </h2>

  <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-7 py-5">
    {% for dialog in dialog_list %}
      {% include "includes/card.html" %}
    {% endfor %}
  </div>
</div>
{% endblock content %}

ambity/templates/includes/card.html
<div class="col">
  <div class="card card-cover h-70 overflow-hidden text-bg-dark rounded-4 shadow-lg">
    <div class="d-flex flex-column h-100 p-5 pb-5 text-white text-shadow-1">
      <a href="{% url 'dialogs:dialog_detail' dialog.pk %}"><h3 class="pt-2 mt-2 mb-2 display-5 fw-bold">{{ dialog }}</h3></a>
      <small>{{ dialog.call_date }}</small>
      <p class="pt-2 mt-2 mb-2">{{ dialog.operator.full_name }}</p>
      <span class="tag tag-danger">{{ dialog.status }}</span>
    </div>
  </div>
</div>

ambity/templates/includes/footer.html

<div class="container fixed-bottom">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">Ambity</p>
  
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
    </footer>
</div>

ambity/templates/includes/header.html
{% load static %}
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 nav-pills">
        <li><a href="{% url 'dialogs:dialog_list' %}" class="nav-link px-2 text-white">Ambity</a></li>
      </ul>
    </div>
  </div>
</header>